apiVersion: v1
kind: ConfigMap
metadata:
  name: web-backup-script-config
data:
  blobcontainerurl: |-
    $$BACKUP_AZURE_CONTAINER_URL
  blobsas: |-
    $$BACKUP_AZURE_BLOB_SAS
  dblist: |-
    $$BACKUP_PG_DBLIST
  dbpassword: |-
    $$BACKUP_PG_PASSWORD
  dbdumpargs: |-
    $$BACKUP_PG_DUMP_ARGS
  backup.sh: |-
    #!/bin/bash

    BLOB_CONTAINER_URL=`cat /backup-assets/blobcontainerurl`
    BLOB_SAS=`cat /backup-assets/blobsas`

    cd /
    datetime=`date +%Y%m%d%H%M`
    mkdir -p /backup/$datetime/club-files/
    mkdir -p /backup/$datetime/db/

    echo "准备中：正在复制网站文件..."
    cp -R /club-data/* /backup/$datetime/club-files/

    export PGPASSWORD=`cat /backup-assets/dbpassword`
    DB_LIST=$(cat /backup-assets/dblist)
    DUMP_ARGS=$(cat /backup-assets/dbdumpargs)
    for DB in $DB_LIST ; do
      echo "准备中：正在为数据库 $DB 生成备份文件..."
      pg_dump --dbname=$DB --encoding=utf-8 -w --format=t $DUMP_ARGS --file=/backup/$datetime/db/${DB}.tar
    done

    echo "打包中..."
    tar -zcf /backup/$datetime.tar.gz /backup/$datetime

    echo '上传中...'
    azcopy copy /backup/$datetime.tar.gz "$BLOB_CONTAINER_URL/dotnetclub/$datetime.tar.gz?$BLOB_SAS"

