apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: web-backup
spec:
  schedule: "0 17 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: web-data
              persistentVolumeClaim: 
                claimName: web-claim
            - name: backup-script
              configMap:
                name: web-backup-script-config
                defaultMode: 0777
          containers:
          - name: backup-runner
            image: dockerhub.azk8s.cn/jijiechen/dotnetclub-backup-runner:azcp10pg11
            imagePullPolicy: IfNotPresent
            volumeMounts:
              - mountPath: /backup-assets/
                name: backup-script
              - mountPath: /club-data
                name: web-data
            args:
              - /backup-assets/backup.sh
                