kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: web-adm-rs
  labels:
    name: web-adm-rs
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: web-adm
  template:
    metadata:
      labels:
        app: web-adm
    spec:
      volumes:
        - name: web-data
          persistentVolumeClaim: 
            claimName: web-claim
      securityContext:
            runAsUser: 5000
            fsGroup: 5000
      containers:
        - name: dotnetclub
          image: jijiechen/dotnetclub-adm:201905061321
          ports:
            - name: http
              containerPort: 5050
          volumeMounts:
            - mountPath: /club-data
              name: web-data
          
