apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: web-certificate-preview
spec:
  secretName: web-certificate-preview
  dnsNames:
    - preview.dotnetclub.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - preview.dotnetclub.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer