kind: Service
apiVersion: v1
metadata:
  name: kibana-svc
  labels:
    name: kibana-svc
spec:
  type: NodePort
  selector:
    app: kibana
    release: efk
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5601
      nodePort: 32001
