apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-claim
  labels:
    name: web-claim
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: alicloud-nas
  resources:
    requests:
      storage: 10Gi