apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  appsettings.json: |-
    {
        "pgsqlConnectionString": "$$CLUB_DB_CONENCTION_STRING",
        "EmailDeliveryOptions": {
          "LoginName": "apikey",
          "Password": "$$SENDGRID_KEY",
          "MailFrom": "system@dotnetclub.net",
          "ServerHost": "smtp.sendgrid.net",
          "ServerSslPort": "465"
        },
        "AliyunSmsOptions": {
          "AccountKeyId": "$$ALIYUN_KEY_ID",
          "AccessKeySecret": "$$ALIYUN_KEY_SECRET",
          "SmsServiceSignName": "$$ALIYUN_SMS_SIGN_CODE",
          "SmsServiceTemplateCode": "$$ALIYUN_SMS_TEMPLATE_CODE"
        },
        "ChatyOptions": {
          "ServiceBaseUrl": "$$CHATY_API_BASE_URL",
          "ApiToken": "$$CHATY_API_TOKEN",
          "AllowedUsers": "$$CHATY_CLUB_USERS"
        },
        "Logging": {
          "File": {
            "PathFormat": "logs/log-{Date}.log",
            "FileSizeLimitBytes": 20971520,
            "OutputTemplate": "[{Level:u3}] {Timestamp:o} {SourceContext} {TraceId}{NewLine}  {Message} {NewLine}{Exception}",
            "LogLevel": {
              "Discussion": "Information",
              "Default": "Warning"
            }
          },
          "Console": {
            "Json": true,
            "ElasticSearchJson": true,
            "LogLevel": {
              "Discussion": "Information",
              "Default": "Warning"
            }
          }
        },
        "DataProtectionOptions": {
          "DisableAutomaticKeyGeneration" : true,
          "KeyRepositoryPath": "/data-protection-keys/",
          "ApplicationName": "dotnetclub"
        },
        "ExternalIdentityServiceOptions": {
          "IsEnabled": true,
          "ProviderId": "id.dotnetclub.net",
          "Authority": "https://id.dotnetclub.net/auth/realms/dotnetclub",
          "RequireHttpsMetadata": true,
          "ClientId": "dotnetclub-net",
          "ClientSecret": "$$EXTERNAL_IDP_CLIENT_SECRET",
          "RegisterUri": "https://id.dotnetclub.net/auth/realms/dotnetclub/protocol/openid-connect/registrations?client_id=dotnetclub-net&response_type=code&scope=openid%20email%20phone%20profile&redirect_uri=https%3A%2F%2Fdotnetclub.net%2Fsignin%3FreturnUrl%3D%252f&kc_locale=zh",
          "ChangePasswordUri": "https://id.dotnetclub.net/auth/realms/dotnetclub/account/password",
          "KeyCloakAdminCredential": "$$EXTERNAL_IDP_ADMIN_CREDENTIAL"
        }
    }