apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: web-certificate-club-id
spec:
  secretName: web-certificate-club-id
  dnsNames:
    - id.dotnetclub.net
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
        - id.dotnetclub.net
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer