apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  appsettings.json: |-
    {
        "sqliteConnectionString": "Data Source=/club-data/dotnetclub.db",
        "Logging": {
          "File": {
            "PathFormat": "logs/log-{Date}.log",
            "FileSizeLimitBytes": 20971520,
            "OutputTemplate": "[{Level:u3}] {Timestamp:o} {SourceContext} {TraceId}{NewLine}  {Message} {NewLine}{Exception}",
            "LogLevel": {
              "Discussion": "Information",
              "Default": "Warning"
            }
          },
          "Console": {
            "Json": true,
            "ElasticSearchJson": true,
            "LogLevel": {
              "Discussion": "Information",
              "Default": "Warning"
            }
          }
        },
        "DataProtectionOptions": {
          "DisableAutomaticKeyGeneration" : true,
          "KeyRepositoryPath": "/data-protection-keys/",
          "ApplicationName": "dotnetclub"
        }
    }