kind: ReplicaSet
apiVersion: apps/v1
metadata:
  name: web-rs
  labels:
    name: web-rs
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      volumes:
        - name: web-data
          persistentVolumeClaim: 
            claimName: web-claim
        - name: web-config-data
          configMap: 
            name: web-config
        - name: web-protection-keys-repo
          secret: 
            secretName: web-protection-keys
      securityContext:
            runAsUser: 5000
            fsGroup: 5000
      initContainers:
        - name: dbmigrator
          image: jijiechen/dotnetclub:201905061321
          command: [ "dotnet"]
          args: ["/club-app/Discussion.Migrations.dll", "Data Source=/club-data/dotnetclub.db"]
          volumeMounts:
            - mountPath: /club-data
              name: web-data
      containers:
        - name: dotnetclub
          image: jijiechen/dotnetclub:201905061321
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - mountPath: /club-data
              name: web-data
            - mountPath: /club-data/appsettings.json
              name: web-config-data
              subPath: appsettings.json
            - mountPath: /data-protection-keys
              name: web-protection-keys-repo
          
