kind: Service
apiVersion: v1
metadata:
  name: web-adm-svc
  labels:
    name: web-adm-svc
spec:
  type: NodePort
  selector:
    app: web-adm
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5050
      nodePort: 31430
