kind: Service
apiVersion: v1
metadata:
  name: pg-release-postgresql-nodeport
  labels:
      app: postgresql
      chart: postgresql-6.0.0
      heritage: Tiller
      release: pg-release
spec:
  type: NodePort
  selector:
      app: postgresql
      release: pg-release
      role: master
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgresql
      nodePort: 30432